version: "3.4"

volumes:
  pg_sandbox_data:
  pg_production_data:

services:
  db:
    image: postgres:11.2
    volumes:
      - "pg_${PLAID_ENV}_data:/var/lib/postgresql/data"
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - .env

  server:
      build: ./server_python
      # image: finchat/server:latest
      ports:
        - 5001:5001
      volumes:
        - ./server_python:/app
      env_file:
        - .env
      depends_on:
        - db

  ngrok:
    build: ./ngrok
    # image: finchat/ngrok:latest
    command: ["ngrok", "http", "server:5001"]
    ports:
      - "127.0.0.1:4040:4040"
    depends_on:
      - server

  client:
    build: 
      context: ./client
    # image: finchat/client:latest
    volumes:
      - ./client:/opt/client         
      - /opt/client/node_modules
    ports:
      - 3001:3001
    env_file:
      - .env
    depends_on:
      - server
