"""Change users_table.id to String

Revision ID: 053a5b9975bd
Revises: 
Create Date: 2025-04-27 21:48:53.663219

"""
from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision = '053a5b9975bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plaid_api_events_table', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plaid_api_events_table', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
